---
title: "LAB3"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
```

## Step 1: Read the data

```{r}
# Install it only if it's not present
if (!require(data.table)){
  install.packages("data.table")
}

library(data.table)
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", method="libcurl", timeout = 60)


met <- data.table::fread("met_all.gz")
```

## Step2: Check the dimensions, headers, footers. How many columns, rows are there?
```{r}
dim(met)
head(met,n=2)
head(met)
tail(met)

```

## Step3: Look at variable
```{r}
str(met)
```

## Step4: Look at Key variables

```{r}
table(met$year)
table(met$day)
summary(met$temp)
summary(met$elev)
summary(met$wind.sp)
```
### Updating NAs in elevation 

```{r}
met$elev[met$elev ==9999.00]<-NA
met[elev == 9999.00, elev :=NA]
summary(met$elev)
```
The higher weather station is at `r max(met$elev, na.rm=TRUE)` `r ifelse(runif(1)> .5, "ft","mts")`.


## Step5: Check the data against an external data source
```{r}
met <- met[temp>-40]
met2 <- met[order(temp)]
head(met2)

met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)

summary(met2[, .(lat, lon, temp,elev,wind.sp)])
```
## Step 6:Calculate summary statistics

```{r}
met[elev==max(elev, na.rm=TRUE)][,summary(wind.sp)]
met[elev==max(elev, na.rm=TRUE)][,summary(temp)]

# correlation
met[elev==max(elev, na.rm=TRUE), .(
  temp_wind=cor(temp, wind.sp, use="complete"),
  temp_day=cor(temp, day, use="complete"),
  temp_hour=cor(temp, hour, use="complete"),
  wind_day=cor(wind.sp, day, use="complete"),
  wind_hour=cor(wind.sp, hour, use="complete")
)]
```
## Step 7:Exploratory graphs

```{r}
hist(met$elev, breaks=100)
hist(met$temp)
hist(met$wind.sp)
```
